baseURL = 'https://cedh-uk.github.io/mtr-ipg'
languageCode = 'en-GB'
title = 'cEDH UK MTR/IPG'
theme = 'hyde'

[menus]
  main = [{name = "GitHub", url= "https://github.com/cedh-uk/mtr-ipg"}]

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false

[markup.goldmark.renderHooks.link]
enableDefault = true